---
title: "Conditions Across City"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(tidyverse)
library(plotly)
```

```{r}
#importing data
report_data <- read_csv("mc1-reports-data.csv")
social_media <- read_csv("YInt.csv")
```

```{r}
#arrange entries in order of time
report_data <- report_data %>%
  arrange(time)
```

```{r}
#working with timestamp
report_data$time %>% head()
report_data <- report_data %>% 
  mutate(Date= as.Date(time)) %>%
  mutate(Time= format(time, format = "%H:%M:%S")) %>%
  mutate(Hours= format(time, format = "%H")) %>%
  mutate(Min= format(time, format = "%M")) 
```


```{r}
#Find when the earthquake occured using frequency of report
freq_report <- report_data %>%
  group_by(time) %>%
  summarize(
    freq = n()
  )

#plot frequency in general - there's a significant increase during April 8
ggplot(freq_report, mapping = aes(x = time, y = freq)) +
  geom_point()
```

```{r}
#plot for April 8th specifically, to see around what time the earthquake might have occured
freq_report0408 <- report_data %>%
  filter(Date == "2020-04-08") %>%
  group_by(time) %>%
  summarize(
    freq = n()
  )

report0408_plot<- ggplot(freq_report0408, mapping = aes(x = time, y = freq)) +
  geom_point()  
ggplotly(report0408_plot)
```
We can estimate that the earthquake occurred around Apr 8th 8:35AM (use 8:30 since easier to handle), since the frequency of reports vastly increase from 7 reports at 8:30AM to 702 reports at 8:35AM.

## In 5hrs
```{r}
#see reports from 8:30AM in 5hrs (na.rm = TRUE)
#Apr 8th 8:30~13:30
report5hrs <- report_data %>%
  filter(Date == "2020-04-08") %>%
  filter(Time >= "08:30:00") %>%
  filter(Time <= "13:30:00")

report5hrs_sum <- report5hrs %>%
  group_by(location) %>%
  summarize(
    sewer_and_water = round(mean(sewer_and_water, na.rm = TRUE), 2),
    power = round(mean(power, na.rm = TRUE), 2),
    roads_and_bridges = round(mean(roads_and_bridges, na.rm = TRUE), 2),
    medical = round(mean(medical, na.rm = TRUE), 2), #medical for location 10 shows as NaN since all are NA
    buildings = round(mean(buildings, na.rm = TRUE), 2)
  ) %>%
  pivot_longer(-location, names_to = "resource", values_to = "damage") #pivot so easy to plot categorical value
```
```{r}
#create df with location names and join them so easy to understand
location <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19)
name <- c("1.Palace Hills", "2.Northwest", "3.Old Town", "4.Safe Town", "5.Southwest", "6.Downtown", "7.Wilson Forest", "8.Scenic Vista", "9.Broadview", "10.Chapparal", "11.Terrapin Springs", "12.Pepper Mill", "13.Cheddarford", "14.Easton", "15.Weston", "16.Southton", "17.Oak Willow", "18.East Parton", "19.West Parton")
location_name <- data.frame(location, name)
report5hrs_sum <- report5hrs_sum %>%
  left_join(location_name, by = "location")
```
```{r}
#plot bar graph
report5hrs_plot <- ggplot(report5hrs_sum, mapping = aes(x = reorder(name,-damage), y = damage, fill = resource)) +
  geom_bar(stat = 'identity') +
  coord_flip()
ggplotly(report5hrs_plot)
```
```{r}
#alternative bar graph with facet wrap
report5hrs_plot2 <- ggplot(report5hrs_sum, mapping = aes(x = reorder(name,-damage), y = damage)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  facet_wrap(~resource)
ggplotly(report5hrs_plot2)
```

## In 30hrs
```{r}
#see reports from 8:30AM in 30hrs (na.rm = TRUE)
#Apr 8th 8:30~ Apr 9th 14:30
filter1 <- report_data %>%
  filter(Date == "2020-04-08") %>%
  filter(Time >= "08:30:00")
filter2 <- report_data %>%  
  filter(Date == "2020-04-09") %>%
  filter(Time <= "14:30:00")
report30hrs <- rbind(filter1, filter2)

report30hrs_sum <- report30hrs %>%
  group_by(location) %>%
  summarize(
    sewer_and_water = round(mean(sewer_and_water, na.rm = TRUE), 2),
    power = round(mean(power, na.rm = TRUE), 2),
    roads_and_bridges = round(mean(roads_and_bridges, na.rm = TRUE), 2),
    medical = round(mean(medical, na.rm = TRUE), 2), #medical for location 10 shows as NaN since all are NA
    buildings = round(mean(buildings, na.rm = TRUE), 2)
  ) %>%
  pivot_longer(-location, names_to = "resource", values_to = "damage") #pivot so easy to plot categorical value
```
```{r}
report30hrs_sum <- report30hrs_sum %>%
  left_join(location_name, by = "location")
```
```{r}
#plot bar graph
report30hrs_plot <- ggplot(report30hrs_sum, mapping = aes(x = reorder(name,-damage), y = damage, fill = resource)) +
  geom_bar(stat = 'identity') +
  coord_flip()
ggplotly(report30hrs_plot)
```
```{r}
#alternative bar graph with facet wrap
report30hrs_plot2 <- ggplot(report30hrs_sum, mapping = aes(x = reorder(name,-damage), y = damage)) + #reorder(name, -location) to order by location
  geom_bar(stat = 'identity') +
  coord_flip() +
  facet_wrap(~resource)
ggplotly(report30hrs_plot2)
```



